apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: inthub-dev
  namespace: kafka
spec:
  kafka:
    version: 3.9.0
    listeners:
      - name: plain
        port: 9092
        type: cluster-ip
        tls: false
    config:
      auto.create.topics.enable: "true"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    storage:
      type: ephemeral
  kafkaNodePools:
    - metadata:
        name: pool-inthub-dev
      spec:
        roles:
          - broker
          - controller
        storage:
          type: ephemeral
        replicas: 1
